services:
  app-db:
    image: "mongo:latest"
    ports:
      - 27017:27017
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

  app-back:
    image: "g0sh3x/devops-demos:backend-image-v1"
    build:
      context: back/target
      dockerfile: ./backend/Dockerfile # relative to context
    ports:
      - ${INGRESS_PORT:-3001}:3001
    depends_on:
      - app-db
    labels:
      kompose.service.expose: "app-${NAMESPACE:-dns}.${ROOT_DNS:-local}/api"
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 512M

  app-front:
    image: "g0sh3x/devops-demos:frontend-image-v1"
    build:
      context: front/
      dockerfile: ./fontend/Dockerfile # relative to context
    depends_on:
      - app-back
    ports:
      - ${INGRESS_PORT:-3000}:3000
    labels:
      kompose.service.expose: "app-${NAMESPACE:-dns}.${ROOT_DNS:-local}"
    deploy:
      resources:
        reservations:
          cpus: "0.01"
          memory: 64M